spring:
  application:
    name: dm-dice-time

---

spring:
  profiles:
    active: cloud
  data:
    mongodb:
      uri: $MONGOLAB_URI
      
---

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost/test